apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-port
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: spring-boot-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app:  spring-boot-demo
  template:
    metadata:
      labels:
        app:  spring-boot-demo
    spec:
      containers:
      - image: <IMAGE_NAME>
        name: spring-boot-demo
        env: 
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://<DNS>:5432/<DB_NAME>?sslmode=require
          - name: SPRING_DATASOURCE_USERNAME
            value: <USERNAME>
          - name: SPRING_DATASOURCE_PASSWORD
            value: <PASSWORD>